/**
 * Card art, keyed by card id.
 *
 * Generated by scripts/pull-card-art.mjs — do not edit by hand. Run `npm run
 * art` after changing an Image column in the sheets.
 *
 * The pictures are the designer's, and the sheets point at postimg. They are
 * not served from postimg: the originals are up to 3 MB at 1280x956, arriving
 * at 200-450 KB/s from a host that sometimes stalls for minutes, and the plate
 * that shows them is 360x270. The script resizes each one to 720px of WebP
 * and puts it in public/cards/, so they ship with the site and Cloudflare
 * serves them from the edge.
 *
 * Two sizes, because there are two plates. A dealt card gets the ${WIDTH}px
 * one; a brief's plate is 92 CSS pixels wide and gets the ${THUMB_WIDTH}px cut
 * of it, which matters because a wall of two dozen briefs is the commonest
 * sight on the sheet.
 *
 * ------------------------------------------------------------------ the gate
 * Nothing here decides who *sees* a picture. Card art is a paid capability
 * (see `showsArt` in tiers.js), checked at the moment of drawing in
 * useCodexArt.js. This file only says what the picture is.
 */

const CARD_ART = {
  'air-control': '/cards/air-control.webp',
  'amber-shard': '/cards/amber-shard.webp',
  'ambush': '/cards/ambush.webp',
  'anticipate': '/cards/anticipate.webp',
  'barkskin': '/cards/barkskin.webp',
  'bird-view': '/cards/bird-view.webp',
  'blazing-suns': '/cards/blazing-suns.webp',
  'bleeding-trail': '/cards/bleeding-trail.webp',
  'blind': '/cards/blind.webp',
  'blood-spear': '/cards/blood-spear.webp',
  'bound-cauldron': '/cards/bound-cauldron.webp',
  'bramble-whip': '/cards/bramble-whip.webp',
  'brew': '/cards/brew.webp',
  'cauterize': '/cards/cauterize.webp',
  'cloak-of-flames': '/cards/cloak-of-flames.webp',
  'control-water': '/cards/control-water.webp',
  'create-water-spell': '/cards/create-water-spell.webp',
  'deepening-connection': '/cards/deepening-connection.webp',
  'distract': '/cards/distract.webp',
  'dodge': '/cards/dodge.webp',
  'draconic-link': '/cards/draconic-link.webp',
  'draconic-mark': '/cards/draconic-mark.webp',
  'draconic-recall': '/cards/draconic-recall.webp',
  'draconic-scale': '/cards/draconic-scale.webp',
  'dragon-breath': '/cards/dragon-breath.webp',
  'dragons-favor': '/cards/dragons-favor.webp',
  'drain-fluids': '/cards/drain-fluids.webp',
  'efficient-brewing': '/cards/efficient-brewing.webp',
  'empowered-bond': '/cards/empowered-bond.webp',
  'entangling-roots': '/cards/entangling-roots.webp',
  'eye-of-the-seeker': '/cards/eye-of-the-seeker.webp',
  'fire-seed': '/cards/fire-seed.webp',
  'flash-freeze': '/cards/flash-freeze.webp',
  'fling': '/cards/fling.webp',
  'force-inebriation': '/cards/force-inebriation.webp',
  'frightful-roar': '/cards/frightful-roar.webp',
  'fungal-bloom': '/cards/fungal-bloom.webp',
  'fungal-invocation': '/cards/fungal-invocation.webp',
  'galvanize': '/cards/galvanize.webp',
  'giant-growth': '/cards/giant-growth.webp',
  'glacial-accretion': '/cards/glacial-accretion.webp',
  'gore-armor': '/cards/gore-armor.webp',
  'grapple': '/cards/grapple.webp',
  'healthy-leaves': '/cards/healthy-leaves.webp',
  'hide': '/cards/hide.webp',
  'hurl': '/cards/hurl.webp',
  'ice-armor': '/cards/ice-armor.webp',
  'ice-block': '/cards/ice-block.webp',
  'ice-shard': '/cards/ice-shard.webp',
  'improved-recipes': '/cards/improved-recipes.webp',
  'interact': '/cards/interact.webp',
  'inventory': '/cards/inventory.webp',
  'investigate': '/cards/investigate.webp',
  'jump': '/cards/jump.webp',
  'kindle-weapon': '/cards/kindle-weapon.webp',
  'lightning-in-a-bottle': '/cards/lightning-in-a-bottle.webp',
  'lightning-strike': '/cards/lightning-strike.webp',
  'magma-chains': '/cards/magma-chains.webp',
  'magma-surge': '/cards/magma-surge.webp',
  'mana-crystal': '/cards/mana-crystal.webp',
  'molten-grasp': '/cards/molten-grasp.webp',
  'move': '/cards/move.webp',
  'mycelial-bond': '/cards/mycelial-bond.webp',
  'mycelium-network': '/cards/mycelium-network.webp',
  'naturalize': '/cards/naturalize.webp',
  'one-and-the-same': '/cards/one-and-the-same.webp',
  'pack-bond': '/cards/pack-bond.webp',
  'parasitic-spore': '/cards/parasitic-spore.webp',
  'primal-roar': '/cards/primal-roar.webp',
  'produce-flame': '/cards/produce-flame.webp',
  'puffball-mushroom': '/cards/puffball-mushroom.webp',
  'purifying-crystal': '/cards/purifying-crystal.webp',
  'quicksilver': '/cards/quicksilver.webp',
  'rain-of-fire': '/cards/rain-of-fire.webp',
  'renew': '/cards/renew.webp',
  'sacred-chalk': '/cards/sacred-chalk.webp',
  'sampled-catalyst': '/cards/sampled-catalyst.webp',
  'savage-slam': '/cards/savage-slam.webp',
  'sense-life': '/cards/sense-life.webp',
  'shape-earth': '/cards/shape-earth.webp',
  'sharpen-sense': '/cards/sharpen-sense.webp',
  'shove': '/cards/shove.webp',
  'skillseed-nut': '/cards/skillseed-nut.webp',
  'skulk': '/cards/skulk.webp',
  'slag-shot': '/cards/slag-shot.webp',
  'sleeping-spores': '/cards/sleeping-spores.webp',
  'snake': '/cards/snake.webp',
  'sporadic-infusion': '/cards/sporadic-infusion.webp',
  'stabilize': '/cards/stabilize.webp',
  'steal': '/cards/steal.webp',
  'sticky-resin': '/cards/sticky-resin.webp',
  'thorn-rampart': '/cards/thorn-rampart.webp',
  'thrilled': '/cards/thrilled.webp',
  'tidal-wave': '/cards/tidal-wave.webp',
  'toxic-toad': '/cards/toxic-toad.webp',
  'vampiric-touch': '/cards/vampiric-touch.webp',
  'verdant-field': '/cards/verdant-field.webp',
  'volcanic-shard': '/cards/volcanic-shard.webp',
  'voltaic-jolt': '/cards/voltaic-jolt.webp',
  'wall-of-flames': '/cards/wall-of-flames.webp',
  'water-vortex': '/cards/water-vortex.webp',
  'wild-strider': '/cards/wild-strider.webp',
  'wild-sweep': '/cards/wild-sweep.webp',
  'wind-blade': '/cards/wind-blade.webp',
  'wisp-of-mist': '/cards/wisp-of-mist.webp',
  'wyrm-bolt': '/cards/wyrm-bolt.webp',
};

/** The art for one card, or null for a card that has none yet. */
export function artFor(id) {
  return CARD_ART[id] ?? null;
}

/** The small cut of it, for the 92px plate a brief draws. */
export function thumbFor(id) {
  const full = CARD_ART[id];
  return full ? full.replace(/\.webp$/, '-thumb.webp') : null;
}

/**
 * The same list of cards with their art attached, for the codex modules to
 * wrap their own arrays in. A card that has no picture keeps `art_url: null`
 * rather than losing the field, so a reader never has to guess whether the
 * absence is missing art or a missing lookup.
 */
export function withArt(cards) {
  return cards.map((card) => ({
    ...card,
    art_url: artFor(card.id),
    art_thumb: thumbFor(card.id),
  }));
}
