/**
 * Card art, keyed by card id.
 *
 * Generated by scripts/pull-card-art.mjs — do not edit by hand. Run `npm run
 * art` after changing an Image column in the sheets.
 *
 * The pictures are the designer's, and the sheets point at postimg. They are
 * not served from postimg: the originals are up to 3 MB at 1280x956, arriving
 * at 200-450 KB/s from a host that sometimes stalls for minutes, and the plate
 * that shows them is 360x270. The script resizes each one to 720px of WebP
 * and puts it in public/cards/, so they ship with the site and Cloudflare
 * serves them from the edge.
 *
 * Two sizes, because there are two plates. A dealt card gets the ${WIDTH}px
 * one; a brief's plate is 92 CSS pixels wide and gets the ${THUMB_WIDTH}px cut
 * of it, which matters because a wall of two dozen briefs is the commonest
 * sight on the sheet.
 *
 * ------------------------------------------------------------------ the gate
 * Nothing here decides who *sees* a picture. Card art is a paid capability
 * (see `showsArt` in tiers.js), checked at the moment of drawing in
 * useCodexArt.js. This file only says what the picture is.
 */

const CARD_ART = {
  'amber-shard': '/cards/amber-shard.webp',
  'anticipate': '/cards/anticipate.webp',
  'barkskin': '/cards/barkskin.webp',
  'bird-view': '/cards/bird-view.webp',
  'bleeding-trail': '/cards/bleeding-trail.webp',
  'blood-spear': '/cards/blood-spear.webp',
  'bound-cauldron': '/cards/bound-cauldron.webp',
  'bramble-whip': '/cards/bramble-whip.webp',
  'brew': '/cards/brew.webp',
  'deepening-connection': '/cards/deepening-connection.webp',
  'draconic-scale': '/cards/draconic-scale.webp',
  'efficient-brewing': '/cards/efficient-brewing.webp',
  'entangling-roots': '/cards/entangling-roots.webp',
  'eye-of-the-seeker': '/cards/eye-of-the-seeker.webp',
  'force-inebriation': '/cards/force-inebriation.webp',
  'fungal-bloom': '/cards/fungal-bloom.webp',
  'fungal-invocation': '/cards/fungal-invocation.webp',
  'giant-growth': '/cards/giant-growth.webp',
  'gore-armor': '/cards/gore-armor.webp',
  'grapple': '/cards/grapple.webp',
  'healthy-leaves': '/cards/healthy-leaves.webp',
  'hide': '/cards/hide.webp',
  'ice-shard': '/cards/ice-shard.webp',
  'improved-recipes': '/cards/improved-recipes.webp',
  'interact': '/cards/interact.webp',
  'inventory': '/cards/inventory.webp',
  'investigate': '/cards/investigate.webp',
  'jump': '/cards/jump.webp',
  'lightning-in-a-bottle': '/cards/lightning-in-a-bottle.webp',
  'mana-crystal': '/cards/mana-crystal.webp',
  'move': '/cards/move.webp',
  'mycelial-bond': '/cards/mycelial-bond.webp',
  'mycelium-network': '/cards/mycelium-network.webp',
  'naturalize': '/cards/naturalize.webp',
  'pack-bond': '/cards/pack-bond.webp',
  'parasitic-spore': '/cards/parasitic-spore.webp',
  'primal-roar': '/cards/primal-roar.webp',
  'puffball-mushroom': '/cards/puffball-mushroom.webp',
  'purifying-crystal': '/cards/purifying-crystal.webp',
  'quicksilver': '/cards/quicksilver.webp',
  'renew': '/cards/renew.webp',
  'sacred-chalk': '/cards/sacred-chalk.webp',
  'sampled-catalyst': '/cards/sampled-catalyst.webp',
  'savage-slam': '/cards/savage-slam.webp',
  'sense-life': '/cards/sense-life.webp',
  'sharpen-sense': '/cards/sharpen-sense.webp',
  'shove': '/cards/shove.webp',
  'skillseed-nut': '/cards/skillseed-nut.webp',
  'sleeping-spores': '/cards/sleeping-spores.webp',
  'snake': '/cards/snake.webp',
  'sporadic-infusion': '/cards/sporadic-infusion.webp',
  'stabilize': '/cards/stabilize.webp',
  'sticky-resin': '/cards/sticky-resin.webp',
  'thorn-rampart': '/cards/thorn-rampart.webp',
  'toxic-toad': '/cards/toxic-toad.webp',
  'vampiric-touch': '/cards/vampiric-touch.webp',
  'verdant-field': '/cards/verdant-field.webp',
  'volcanic-shard': '/cards/volcanic-shard.webp',
  'wild-strider': '/cards/wild-strider.webp',
  'wild-sweep': '/cards/wild-sweep.webp',
  'wisp-of-mist': '/cards/wisp-of-mist.webp',
};

/** The art for one card, or null for a card that has none yet. */
export function artFor(id) {
  return CARD_ART[id] ?? null;
}

/** The small cut of it, for the 92px plate a brief draws. */
export function thumbFor(id) {
  const full = CARD_ART[id];
  return full ? full.replace(/\.webp$/, '-thumb.webp') : null;
}

/**
 * The same list of cards with their art attached, for the codex modules to
 * wrap their own arrays in. A card that has no picture keeps `art_url: null`
 * rather than losing the field, so a reader never has to guess whether the
 * absence is missing art or a missing lookup.
 */
export function withArt(cards) {
  return cards.map((card) => ({
    ...card,
    art_url: artFor(card.id),
    art_thumb: thumbFor(card.id),
  }));
}
