/**
 * Item art, keyed by item id.
 *
 * Generated by scripts/pull-item-art.mjs — do not edit by hand. Run `npm run
 * art:items` after adding a picture to a folder under data/.
 *
 * The pictures are the designer's, and they arrive as a folder of 2048x2048
 * JPEGs — 2.4 MB apiece. They are not served that way: the plates that draw
 * them are a 40px icon tile and a 360px item card, so the script cuts each one
 * to 720px and 128px of WebP in public/items/ and the whole set
 * ships with the site for Cloudflare to serve from the edge.
 *
 * Two sizes, because there are two plates, and the small one is not a nicety:
 * a browser list is nine tiles at once and every block in the inventory draws
 * one, so the tile is the commonest picture on the sheet and the card is the
 * rarest.
 *
 * ------------------------------------------------------------- the ?v=
 * Every URL carries eight characters of its file's content hash. A redraw
 * keeps the filename and changes the pixels, which no cache can see, so
 * without this a reader who had already loaded a picture kept the old one
 * until their browser felt like asking again. Same bytes, same URL; new
 * bytes, new URL, and every cache misses at once. See the note over the
 * version helper in scripts/pull-item-art.mjs.
 *
 * ------------------------------------------------------------------ the gate
 * Nothing here decides who *sees* a picture. Codex art is a paid capability
 * (see `showsArt` in tiers.js), checked at the moment of drawing in
 * useCodexArt.js. This file only says what the picture is.
 */

const ITEM_ART = {
  'bottled-lightning': '/items/bottled-lightning.webp?v=3fcf3e0b',
  'brightscale-draught': '/items/brightscale-draught.webp?v=bbdb3ee5',
  'chainmail-chausses': '/items/chainmail-chausses.webp?v=24da266d',
  'chainmail-coif': '/items/chainmail-coif.webp?v=7e6f6962',
  'chainmail-hauberk': '/items/chainmail-hauberk.webp?v=ed7f519c',
  'defense-draught': '/items/defense-draught.webp?v=f3ffca53',
  'draught-of-cleansing': '/items/draught-of-cleansing.webp?v=e0fba1e6',
  'elixir-of-chaos': '/items/elixir-of-chaos.webp?v=35125f61',
  'elixir-of-slime': '/items/elixir-of-slime.webp?v=4a3d9819',
  'elixir-of-time': '/items/elixir-of-time.webp?v=5c57c17e',
  'etherealness-potion': '/items/etherealness-potion.webp?v=39663737',
  'explosive-concoction': '/items/explosive-concoction.webp?v=125f0561',
  'full-plate-cuirass': '/items/full-plate-cuirass.webp?v=fdaa060d',
  'full-plate-helm': '/items/full-plate-helm.webp?v=389ef554',
  'full-plate-pants': '/items/full-plate-pants.webp?v=0c82926b',
  'greater-runed-hood': '/items/greater-runed-hood.webp?v=64446e4b',
  'greater-runed-leggings': '/items/greater-runed-leggings.webp?v=6ad33ac3',
  'greater-runed-robes': '/items/greater-runed-robes.webp?v=04c588ae',
  'growth-elixir': '/items/growth-elixir.webp?v=e64af54f',
  'half-plate-cuirass': '/items/half-plate-cuirass.webp?v=f073838d',
  'half-plate-greaves': '/items/half-plate-greaves.webp?v=4677e7b0',
  'half-plate-helm': '/items/half-plate-helm.webp?v=f843fc22',
  'healing-potion': '/items/healing-potion.webp?v=69ea52e0',
  'leather-helm': '/items/leather-helm.webp?v=54b51438',
  'leather-pants': '/items/leather-pants.webp?v=5ce5ad62',
  'leather-vest': '/items/leather-vest.webp?v=23f8bae6',
  'life-draught': '/items/life-draught.webp?v=78b0a432',
  'life-tree-tea': '/items/life-tree-tea.webp?v=3b421a52',
  'love-potion': '/items/love-potion.webp?v=1cf812bc',
  'luck-potion': '/items/luck-potion.webp?v=b4ca9d38',
  'poison': '/items/poison.webp?v=5855a129',
  'potion-of-disguise': '/items/potion-of-disguise.webp?v=5d0c0c88',
  'potion-of-flying': '/items/potion-of-flying.webp?v=b84ed05e',
  'power-draught': '/items/power-draught.webp?v=4139af36',
  'runed-hood': '/items/runed-hood.webp?v=9a83cbee',
  'runed-leggings': '/items/runed-leggings.webp?v=1d740e79',
  'runed-robes': '/items/runed-robes.webp?v=24ec88c5',
  'scale-armor': '/items/scale-armor.webp?v=ee25bd18',
  'scale-helm': '/items/scale-helm.webp?v=88a6abc6',
  'scale-leggings': '/items/scale-leggings.webp?v=fbf76754',
  'seafarers-elixir': '/items/seafarers-elixir.webp?v=d0c93b94',
  'shrink-elixir': '/items/shrink-elixir.webp?v=d3ff8bcd',
  'skinstone-draught': '/items/skinstone-draught.webp?v=f43318c4',
  'studded-leather-breeches': '/items/studded-leather-breeches.webp?v=12b4a260',
  'studded-leather-helm': '/items/studded-leather-helm.webp?v=23fb57c8',
  'studded-leather-tunic': '/items/studded-leather-tunic.webp?v=6c4b5efd',
  'supreme-runed-hood': '/items/supreme-runed-hood.webp?v=75932e00',
  'supreme-runed-leggings': '/items/supreme-runed-leggings.webp?v=22ba9870',
  'supreme-runed-robes': '/items/supreme-runed-robes.webp?v=1cd5d779',
  'titansbane-poison': '/items/titansbane-poison.webp?v=9e8147b9',
  'vulnerability-potion': '/items/vulnerability-potion.webp?v=c344e7ed',
};

/** The art for one item, or null for an item that has none yet. */
export function artFor(id) {
  return ITEM_ART[id] ?? null;
}

/** The small square cut of it, for the 64px icon tiles. */
export function thumbFor(id) {
  const full = ITEM_ART[id];
  return full ? full.replace(/\.webp(\?|$)/, '-thumb.webp$1') : null;
}

/**
 * The same list of items with their art attached, for the codex to wrap its
 * own arrays in. An item that has no picture keeps `art_url: null` rather
 * than losing the field, so a reader never has to guess whether the absence is
 * missing art or a missing lookup.
 */
export function withArt(items) {
  return items.map((item) => ({
    ...item,
    art_url: artFor(item.id),
    art_thumb: thumbFor(item.id),
  }));
}
