/**
 * Item art, keyed by item id.
 *
 * Generated by scripts/pull-item-art.mjs — do not edit by hand. Run `npm run
 * art:items` after changing what feeds it, then `npm run art:push` to send the
 * pictures themselves.
 *
 * ------------------------------------------------------------------ the bucket
 * Every entry here is a `codex:` reference into a **private Supabase bucket**,
 * not a path into public/. The pictures are AI generated placeholder art made
 * for one table, and this repository is public: shipping them inside it meant
 * the art rule decided whether a plate was *drawn* while the file behind it
 * stayed readable by anybody who guessed a path or simply browsed the code.
 *
 * So a reference names an object and useCodexArt signs it at the moment of
 * drawing, which the policy on the bucket has to allow first. The naming law is
 * src/lib/codexArt.js and the policy is the CODEX ART section of
 * supabase/schema.sql.
 *
 * Two cuts, because there are two plates:
 *
 *   .full.webp   720px, the item card
 *   .thumb.webp  128px, the 40px icon tile
 *
 * ------------------------------------------------------------ the other home
 * An entry **without** the `codex:` prefix is a plain path into public/ and is
 * served from the edge exactly as everything here used to be. That is where
 * commissioned art goes: it is owned, it is meant to be seen, and it wants a
 * cache rather than a signature. There is none yet. The day there is, that one
 * entry changes shape and nothing that reads this file is touched.
 *
 * ------------------------------------------------------------------ the gate
 * Nothing here decides who *sees* a picture. Codex art is a friend capability
 * (see `showsArt` in tiers.js), checked at the moment of drawing in
 * useCodexArt.js, and enforced for real by the bucket's own policy. This file
 * only says what the picture is.
 */

const ITEM_ART = {
  'bottled-lightning': 'codex:items/bottled-lightning.full.webp',
  'brightscale-draught': 'codex:items/brightscale-draught.full.webp',
  'chainmail-chausses': 'codex:items/chainmail-chausses.full.webp',
  'chainmail-coif': 'codex:items/chainmail-coif.full.webp',
  'chainmail-hauberk': 'codex:items/chainmail-hauberk.full.webp',
  'defense-draught': 'codex:items/defense-draught.full.webp',
  'draught-of-cleansing': 'codex:items/draught-of-cleansing.full.webp',
  'elixir-of-chaos': 'codex:items/elixir-of-chaos.full.webp',
  'elixir-of-slime': 'codex:items/elixir-of-slime.full.webp',
  'elixir-of-time': 'codex:items/elixir-of-time.full.webp',
  'etherealness-potion': 'codex:items/etherealness-potion.full.webp',
  'explosive-concoction': 'codex:items/explosive-concoction.full.webp',
  'full-plate-cuirass': 'codex:items/full-plate-cuirass.full.webp',
  'full-plate-helm': 'codex:items/full-plate-helm.full.webp',
  'full-plate-pants': 'codex:items/full-plate-pants.full.webp',
  'greater-runed-hood': 'codex:items/greater-runed-hood.full.webp',
  'greater-runed-leggings': 'codex:items/greater-runed-leggings.full.webp',
  'greater-runed-robes': 'codex:items/greater-runed-robes.full.webp',
  'growth-elixir': 'codex:items/growth-elixir.full.webp',
  'half-plate-cuirass': 'codex:items/half-plate-cuirass.full.webp',
  'half-plate-greaves': 'codex:items/half-plate-greaves.full.webp',
  'half-plate-helm': 'codex:items/half-plate-helm.full.webp',
  'healing-potion': 'codex:items/healing-potion.full.webp',
  'leather-helm': 'codex:items/leather-helm.full.webp',
  'leather-pants': 'codex:items/leather-pants.full.webp',
  'leather-vest': 'codex:items/leather-vest.full.webp',
  'life-draught': 'codex:items/life-draught.full.webp',
  'life-tree-tea': 'codex:items/life-tree-tea.full.webp',
  'love-potion': 'codex:items/love-potion.full.webp',
  'luck-potion': 'codex:items/luck-potion.full.webp',
  'poison': 'codex:items/poison.full.webp',
  'potion-of-disguise': 'codex:items/potion-of-disguise.full.webp',
  'potion-of-flying': 'codex:items/potion-of-flying.full.webp',
  'power-draught': 'codex:items/power-draught.full.webp',
  'runed-hood': 'codex:items/runed-hood.full.webp',
  'runed-leggings': 'codex:items/runed-leggings.full.webp',
  'runed-robes': 'codex:items/runed-robes.full.webp',
  'scale-armor': 'codex:items/scale-armor.full.webp',
  'scale-helm': 'codex:items/scale-helm.full.webp',
  'scale-leggings': 'codex:items/scale-leggings.full.webp',
  'seafarers-elixir': 'codex:items/seafarers-elixir.full.webp',
  'shrink-elixir': 'codex:items/shrink-elixir.full.webp',
  'skinstone-draught': 'codex:items/skinstone-draught.full.webp',
  'studded-leather-breeches': 'codex:items/studded-leather-breeches.full.webp',
  'studded-leather-helm': 'codex:items/studded-leather-helm.full.webp',
  'studded-leather-tunic': 'codex:items/studded-leather-tunic.full.webp',
  'supreme-runed-hood': 'codex:items/supreme-runed-hood.full.webp',
  'supreme-runed-leggings': 'codex:items/supreme-runed-leggings.full.webp',
  'supreme-runed-robes': 'codex:items/supreme-runed-robes.full.webp',
  'titansbane-poison': 'codex:items/titansbane-poison.full.webp',
  'vulnerability-potion': 'codex:items/vulnerability-potion.full.webp',
};

/** The art for one item, or null for an item that has none yet. */
export function artFor(id) {
  return ITEM_ART[id] ?? null;
}

/** The small cut of it, for the 40px icon tiles. */
export function thumbFor(id) {
  const full = ITEM_ART[id];
  return full ? full.replace(/\.full\.webp$/, '.thumb.webp') : null;
}

/**
 * The same list of items with their art attached, for the codex to wrap its
 * own arrays in. An item that has no picture keeps `art_url: null` rather than
 * losing the field, so a reader never has to guess whether the absence is
 * missing art or a missing lookup.
 */
export function withArt(items) {
  return items.map((item) => ({
    ...item,
    art_url: artFor(item.id),
    art_thumb: thumbFor(item.id),
  }));
}
