/**
 * Item art, keyed by item id.
 *
 * Generated by scripts/pull-item-art.mjs — do not edit by hand. Run `npm run
 * art:items` after adding a picture to a folder under data/.
 *
 * The pictures are the designer's, and they arrive as a folder of 2048x2048
 * JPEGs — 2.4 MB apiece. They are not served that way: the plates that draw
 * them are a 40px icon tile and a 360px item card, so the script cuts each one
 * to 720px and 128px of WebP in public/items/ and the whole set
 * ships with the site for Cloudflare to serve from the edge.
 *
 * Two sizes, because there are two plates, and the small one is not a nicety:
 * a browser list is nine tiles at once and every block in the inventory draws
 * one, so the tile is the commonest picture on the sheet and the card is the
 * rarest.
 *
 * ------------------------------------------------------------------ the gate
 * Nothing here decides who *sees* a picture. Codex art is a paid capability
 * (see `showsArt` in tiers.js), checked at the moment of drawing in
 * useCodexArt.js. This file only says what the picture is.
 */

const ITEM_ART = {
  'chainmail-chausses': '/items/chainmail-chausses.webp',
  'chainmail-coif': '/items/chainmail-coif.webp',
  'chainmail-hauberk': '/items/chainmail-hauberk.webp',
  'full-plate-cuirass': '/items/full-plate-cuirass.webp',
  'full-plate-helm': '/items/full-plate-helm.webp',
  'full-plate-pants': '/items/full-plate-pants.webp',
  'greater-runed-hood': '/items/greater-runed-hood.webp',
  'greater-runed-leggings': '/items/greater-runed-leggings.webp',
  'greater-runed-robes': '/items/greater-runed-robes.webp',
  'half-plate-cuirass': '/items/half-plate-cuirass.webp',
  'half-plate-greaves': '/items/half-plate-greaves.webp',
  'half-plate-helm': '/items/half-plate-helm.webp',
  'leather-helm': '/items/leather-helm.webp',
  'leather-pants': '/items/leather-pants.webp',
  'leather-vest': '/items/leather-vest.webp',
  'runed-hood': '/items/runed-hood.webp',
  'runed-leggings': '/items/runed-leggings.webp',
  'runed-robes': '/items/runed-robes.webp',
  'scale-armor': '/items/scale-armor.webp',
  'scale-helm': '/items/scale-helm.webp',
  'scale-leggings': '/items/scale-leggings.webp',
  'studded-leather-breeches': '/items/studded-leather-breeches.webp',
  'studded-leather-helm': '/items/studded-leather-helm.webp',
  'studded-leather-tunic': '/items/studded-leather-tunic.webp',
  'supreme-runed-hood': '/items/supreme-runed-hood.webp',
  'supreme-runed-leggings': '/items/supreme-runed-leggings.webp',
  'supreme-runed-robes': '/items/supreme-runed-robes.webp',
};

/** The art for one item, or null for an item that has none yet. */
export function artFor(id) {
  return ITEM_ART[id] ?? null;
}

/** The small square cut of it, for the 64px icon tiles. */
export function thumbFor(id) {
  const full = ITEM_ART[id];
  return full ? full.replace(/\.webp$/, '-thumb.webp') : null;
}

/**
 * The same list of items with their art attached, for the codex to wrap its
 * own arrays in. An item that has no picture keeps `art_url: null` rather
 * than losing the field, so a reader never has to guess whether the absence is
 * missing art or a missing lookup.
 */
export function withArt(items) {
  return items.map((item) => ({
    ...item,
    art_url: artFor(item.id),
    art_thumb: thumbFor(item.id),
  }));
}
